# Deploy-CurrentCommit.ps1
#Requires -Version 7.0
$ErrorActionPreference = "Stop"

# 目标脚本路径（本地应用程序数据目录）
$targetDir = Join-Path $env:LOCALAPPDATA "Scripts"

# 检查未提交文件
$uncommitted = git status --porcelain | Where-Object { $_ -notmatch "^.. Deploy-CurrentCommit\.ps1$" } # 忽略自身方便测试
if ($uncommitted) {
    Write-Host "❌ 存在未提交的修改，请先提交或暂存后再部署：" -ForegroundColor Red
    Write-Host $uncommitted
    exit 1
}

$currentHead = git rev-parse HEAD
$shortHead = $currentHead.Substring(0, 7)

#region 工作树

# 如果目标目录不存在，创建并初始化工作树
if (-not (Test-Path $targetDir -PathType Container)) {
    # 使用 git worktree 创建新工作树
    git worktree add --detach $targetDir $currentHead
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ 创建工作树失败" -ForegroundColor Red
        exit 1
    }
    Write-Host "🌱 创建新工作树: $targetDir"
}
else {
    # 直接更新现有工作树到当前HEAD
    $previousHead = git -C $targetDir rev-parse HEAD
    if ($previousHead -eq $currentHead) {
        Write-Host "⏩ 工作树已经位于 $shortHead，无需更新"
    }
    else {
        git -C $targetDir checkout --detach $currentHead
        if ($LASTEXITCODE -ne 0) {
            Write-Host "❌ 目标目录更新失败，请检查以上Git错误信息" -ForegroundColor Red
            exit 2
        }
        Write-Host "🔄 更新工作树到当前HEAD ($($previousHead.Substring(0,7)) -> $shortHead)"
    }
}
#endregion

#region 配置 PowerShell Profile
$profileScriptPath = Join-Path $targetDir "profiles\Microsoft.PowerShell_profile.ps1"
if (Test-Path $profileScriptPath) {
    $markerStart = "#region 🚀 Auto-Generated by Deploy-CurrentCommit.ps1 (64094a1431f6), DO NOT EDIT."
    $markerEnd = "#endregion 🚀"
    $profileBlock = @"
$markerStart
`$ScriptsRoot = "$targetDir"
. "`$ScriptsRoot\profiles\Microsoft.PowerShell_profile.ps1"
$markerEnd
"@ 
    
    # 读取当前 profile 内容
    $profileContent = if (Test-Path $PROFILE) { 
        (Get-Content $PROFILE -Raw) -replace "`r`n", "`n" # 忽略换行符差异
    }
    else { 
        "" 
    }
    
    # 检查是否已存在标记块
    if ($profileContent -match [regex]::Escape($markerStart)) {
        # 更新现有块
        $pattern = "(?s)" + [regex]::Escape($markerStart) + ".*?" + [regex]::Escape($markerEnd)
        $updatedContent = $profileContent -replace $pattern, $profileBlock
        if ($updatedContent -ne $profileContent) {
            $updatedContent | Set-Content $PROFILE
            Write-Host "✅ 更新 PowerShell Profile 引用"
        }
        else {
            Write-Host "⏩ PowerShell Profile 引用已是最新"
        }
    }
    else {
        # 添加新块到文件末尾
        $newContent = if ($profileContent.Trim().Length -gt 0) {
            $profileContent.Trim() + "`n`n" + $profileBlock
        }
        else {
            $profileBlock
        }
        $newContent | Set-Content -NoNewline $PROFILE
        Write-Host "✅ 添加 PowerShell Profile 引用"
    }
}
else {
    Write-Host "⚠️  未找到 $profileScriptPath，跳过 Profile 配置" -ForegroundColor Yellow
}
# endregion

#region 计划任务管理
$taskName = "每日运行自定义脚本_015aa3e1"
$targetScript = Join-Path $targetDir "automation\Invoke-DailyTask.ps1"
$currentDescription = "每日执行维护脚本 (Commit: $shortHead)"
# 检查脚本是否存在
if (Test-Path $targetScript) {
    # 创建新的任务动作
    $newAction = New-ScheduledTaskAction -Execute "$PSHOME\pwsh.exe" `
        -Argument "-File `"$targetScript`""
    
    $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    
    if (-not $task) {
        # 创建新任务
        $trigger = New-ScheduledTaskTrigger -Daily -At 04:00
        $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
        $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive
        
        Register-ScheduledTask `
            -TaskName $taskName `
            -Action $newAction `
            -Trigger $trigger `
            -Settings $settings `
            -Principal $principal `
            -Description $currentDescription
        
        Write-Host "✅ 计划任务已创建: $taskName"
    }
    elseif ($task.Description -ne $currentDescription) {
        # 更新动作和描述
        $task.Actions = $newAction
        $task.Description = $currentDescription
        # 不更新触发器，允许用户自定义

        # 保存更新
        $null = Set-ScheduledTask $task
            
        Write-Host "🔄 更新计划任务: $taskName"
    }
    else {
        Write-Host "⏩ 计划任务 $taskName 已是最新版本"
    }   
}
else {
    Write-Host "⚠️  未找到 $targetScript，跳过计划任务管理" -ForegroundColor Yellow
}

#endregion

Write-Host "🎉 部署完成！脚本已更新到版本 $shortHead。" -ForegroundColor Green
