# Deploy-CurrentCommit.ps1
#Requires -Version 7.0
$ErrorActionPreference = "Stop"



# 目标脚本路径（本地应用程序数据目录）
$targetDir = Join-Path $env:LOCALAPPDATA "Scripts"

# 检查未提交文件
$uncommitted = git status --porcelain | Where-Object { $_ -notmatch "^.. Deploy-CurrentCommit\.ps1$" } # 忽略自身方便测试
if ($uncommitted) {
    Write-Host "❌ 存在未提交的修改，请先提交或暂存后再部署：" -ForegroundColor Red
    Write-Host $uncommitted
    exit 1
}

$currentHead = git rev-parse HEAD
$shortHead = $currentHead.Substring(0, 7)

#region 工作树

# 如果目标目录不存在，创建并初始化工作树
if (-not (Test-Path $targetDir -PathType Container)) {
    # 使用 git worktree 创建新工作树
    git worktree add --detach $targetDir $currentHead
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ 创建工作树失败" -ForegroundColor Red
        exit 1
    }
    Write-Host "🌱 创建新工作树: $targetDir"
}
else {
    # 直接更新现有工作树到当前HEAD
    $previousHead = git -C $targetDir rev-parse HEAD
    if ($previousHead -eq $currentHead) {
        Write-Host "⏩ 工作树已经位于 $shortHead，无需更新"
    }
    else {
        git -C $targetDir checkout --detach $currentHead
        if ($LASTEXITCODE -ne 0) {
            Write-Host "❌ 目标目录更新失败，请检查以上Git错误信息" -ForegroundColor Red
            exit 2
        }
        Write-Host "🔄 更新工作树到当前HEAD ($($previousHead.Substring(0,7)) -> $shortHead)"
    }
}
#endregion

#region 配置 PowerShell Profile
$profileScriptPath = Join-Path $targetDir "profiles\Microsoft.PowerShell_profile.ps1"
if (Test-Path $profileScriptPath) {
    $markerStart = "#region 🚀 Auto-Generated by Deploy-CurrentCommit.ps1 (64094a1431f6), DO NOT EDIT."
    $markerEnd = "#endregion 🚀"
    $profileBlock = @"
$markerStart
`$ScriptsRoot = "$targetDir"
. "`$ScriptsRoot\profiles\Microsoft.PowerShell_profile.ps1"
$markerEnd
"@ 
    
    # 读取当前 profile 内容
    $profileContent = if (Test-Path $PROFILE) { 
        (Get-Content $PROFILE -Raw) -replace "`r`n", "`n" # 忽略换行符差异
    }
    else { 
        "" 
    }
    
    # 检查是否已存在标记块
    if ($profileContent -match [regex]::Escape($markerStart)) {
        # 更新现有块
        $pattern = "(?s)" + [regex]::Escape($markerStart) + ".*?" + [regex]::Escape($markerEnd)
        $updatedContent = $profileContent -replace $pattern, $profileBlock
        if ($updatedContent -ne $profileContent) {
            $updatedContent | Set-Content $PROFILE
            Write-Host "✅ 更新 PowerShell Profile 引用"
        }
        else {
            Write-Host "⏩ PowerShell Profile 引用已是最新"
        }
    }
    else {
        # 添加新块到文件末尾
        $newContent = if ($profileContent.Trim().Length -gt 0) {
            $profileContent.Trim() + "`n`n" + $profileBlock
        }
        else {
            $profileBlock
        }
        $newContent | Set-Content -NoNewline $PROFILE
        Write-Host "✅ 添加 PowerShell Profile 引用"
    }
}
else {
    Write-Host "⚠️  未找到 $profileScriptPath，跳过 Profile 配置" -ForegroundColor Yellow
}
# endregion

#region 计划任务管理
$taskName = "每日运行自定义脚本_015aa3e1"
$targetScript = Join-Path $targetDir "automation\Invoke-DailyTask.ps1"
$currentDescription = "每日执行维护脚本 (Commit: $shortHead)"
# 检查脚本是否存在
if (Test-Path $targetScript) {
    # 创建新的任务动作
    $newAction = New-ScheduledTaskAction -Execute "$PSHOME\pwsh.exe" `
        -Argument "-File `"$targetScript`""
    
    $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    
    if (-not $task) {
        # 创建新任务
        $trigger = New-ScheduledTaskTrigger -Daily -At 04:00
        $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
        $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive
        
        Register-ScheduledTask `
            -TaskName $taskName `
            -Action $newAction `
            -Trigger $trigger `
            -Settings $settings `
            -Principal $principal `
            -Description $currentDescription
        
        Write-Host "✅ 计划任务已创建: $taskName"
    }
    elseif ($task.Description -ne $currentDescription) {
        # 更新动作和描述
        $task.Actions = $newAction
        $task.Description = $currentDescription
        # 不更新触发器，允许用户自定义

        # 保存更新
        $null = Set-ScheduledTask $task
            
        Write-Host "🔄 更新计划任务: $taskName"
    }
    else {
        Write-Host "⏩ 计划任务 $taskName 已是最新版本"
    }   
}
else {
    Write-Host "⚠️  未找到 $targetScript，跳过计划任务管理" -ForegroundColor Yellow
}

#endregion

#endregion

#region 登录任务管理 (计划任务方式)
$regPath = "HKCU:\Environment"
$regValueName = "UserInitMprLogonScript"
if (Get-ItemProperty -Path $regPath -Name $regValueName -ErrorAction SilentlyContinue) {
    Remove-ItemProperty -Path $regPath -Name $regValueName
    Write-Host "🧹 已清理 UserInitMprLogonScript 注册表项"
}

$loginTaskName = "会话状态同步_ea8baf975afe"
$loginTargetScript = Join-Path $targetDir "automation\Update-SessionState.ps1"
$loginDescription = "根据会话状态自动同步 PowerToys Awake 和 Stretchly (Commit: $shortHead)"

# 清理过时的任务名称
$obsoleteTasks = @("用户登录初始化任务_c6ed3a2b", "远程会话防睡眠_ea8baf975afe", "按需保持唤醒_ea8baf975afe")
foreach ($oldTask in $obsoleteTasks) {
    if (Get-ScheduledTask -TaskName $oldTask -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $oldTask -Confirm:$false
        Write-Host "🗑️ 已移除过时任务: $oldTask"
    }
}

if (Test-Path $loginTargetScript) {
    $loginAction = New-ScheduledTaskAction -Execute "$PSHOME\pwsh.exe" `
        -Argument "-WindowStyle Hidden -ExecutionPolicy Bypass -File `"$loginTargetScript`""
    
    # 使用 XML 方式定义任务，以完美支持多种高级触发器并避开 PowerShell 类型绑定 Bug
    $currentUser = "$env:USERDOMAIN\$env:USERNAME"
    $taskXml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>$loginDescription</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>$currentUser</UserId>
    </LogonTrigger>
    <SessionStateChangeTrigger>
      <Enabled>true</Enabled>
      <StateChange>ConsoleConnect</StateChange>
      <UserId>$currentUser</UserId>
    </SessionStateChangeTrigger>
    <SessionStateChangeTrigger>
      <Enabled>true</Enabled>
      <StateChange>RemoteConnect</StateChange>
      <UserId>$currentUser</UserId>
    </SessionStateChangeTrigger>
    <SessionStateChangeTrigger>
      <Enabled>true</Enabled>
      <StateChange>RemoteDisconnect</StateChange>
      <UserId>$currentUser</UserId>
    </SessionStateChangeTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>$currentUser</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>$PSHOME\pwsh.exe</Command>
      <Arguments>-WindowStyle Hidden -ExecutionPolicy Bypass -File "$loginTargetScript"</Arguments>
    </Exec>
  </Actions>
</Task>
"@

    $existingTask = Get-ScheduledTask -TaskName $loginTaskName -ErrorAction SilentlyContinue
    
    if (-not $existingTask -or $existingTask.Description -ne $loginDescription) {
        $null = Register-ScheduledTask -Xml $taskXml -TaskName $loginTaskName -Force
        if (-not $existingTask) {
            Write-Host "✅ 已通过 XML 创建登录计划任务: $loginTaskName"
        } else {
            Write-Host "🔄 已通过 XML 更新登录计划任务: $loginTaskName"
        }
    }
    else {
        Write-Host "⏩ 登录计划任务已是最新版本"
    }
}
else {
    Write-Host "⚠️  未找到脚本 $loginTargetScript，跳过登录任务管理" -ForegroundColor Yellow
}
#endregion

Write-Host "🎉 部署完成！脚本已更新到版本 $shortHead。" -ForegroundColor Green
