# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\zhouxuan.WLF\CloudSync\Scripts\video-processing\SceneTools\SceneTools.ui'
#
# Created: Wed May 31 17:55:48 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(488, 407)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(60, 20, 351, 161))
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 20, 122, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.epEdit = QtGui.QLineEdit(self.layoutWidget)
        self.epEdit.setObjectName("epEdit")
        self.horizontalLayout.addWidget(self.epEdit)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scEdit = QtGui.QLineEdit(self.layoutWidget)
        self.scEdit.setObjectName("scEdit")
        self.horizontalLayout.addWidget(self.scEdit)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 165, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.projectEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.projectEdit.setObjectName("projectEdit")
        self.horizontalLayout_4.addWidget(self.projectEdit)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 60, 321, 92))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_nuke = QtGui.QVBoxLayout()
        self.verticalLayout_nuke.setObjectName("verticalLayout_nuke")
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_nuke.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nukeEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.nukeEdit.setDragEnabled(True)
        self.nukeEdit.setObjectName("nukeEdit")
        self.horizontalLayout_2.addWidget(self.nukeEdit)
        self.nukeButton = QtGui.QToolButton(self.layoutWidget2)
        self.nukeButton.setObjectName("nukeButton")
        self.horizontalLayout_2.addWidget(self.nukeButton)
        self.verticalLayout_nuke.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_nuke)
        self.verticalLayout_nuke_2 = QtGui.QVBoxLayout()
        self.verticalLayout_nuke_2.setObjectName("verticalLayout_nuke_2")
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_nuke_2.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.serverEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.serverEdit.setDragEnabled(True)
        self.serverEdit.setObjectName("serverEdit")
        self.horizontalLayout_3.addWidget(self.serverEdit)
        self.serverButton = QtGui.QToolButton(self.layoutWidget2)
        self.serverButton.setObjectName("serverButton")
        self.horizontalLayout_3.addWidget(self.serverButton)
        self.verticalLayout_nuke_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_nuke_2)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 190, 221, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.sheetButton = QtGui.QPushButton(self.groupBox_2)
        self.sheetButton.setGeometry(QtCore.QRect(30, 110, 150, 60))
        self.sheetButton.setBaseSize(QtCore.QSize(0, 0))
        self.sheetButton.setIconSize(QtCore.QSize(16, 16))
        self.sheetButton.setObjectName("sheetButton")
        self.csheetUp_check = QtGui.QCheckBox(self.groupBox_2)
        self.csheetUp_check.setGeometry(QtCore.QRect(50, 50, 107, 16))
        self.csheetUp_check.setObjectName("csheetUp_check")
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 190, 221, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.uploadButton = QtGui.QPushButton(self.groupBox_3)
        self.uploadButton.setGeometry(QtCore.QRect(40, 110, 150, 60))
        self.uploadButton.setObjectName("uploadButton")
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 20, 104, 80))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.videoUp_check = QtGui.QCheckBox(self.layoutWidget3)
        self.videoUp_check.setObjectName("videoUp_check")
        self.horizontalLayout_6.addWidget(self.videoUp_check)
        self.imageUp_check = QtGui.QCheckBox(self.layoutWidget3)
        self.imageUp_check.setObjectName("imageUp_check")
        self.horizontalLayout_6.addWidget(self.imageUp_check)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.videoDown_check = QtGui.QCheckBox(self.layoutWidget3)
        self.videoDown_check.setObjectName("videoDown_check")
        self.horizontalLayout_8.addWidget(self.videoDown_check)
        self.imageDown_check = QtGui.QCheckBox(self.layoutWidget3)
        self.imageDown_check.setObjectName("imageDown_check")
        self.horizontalLayout_8.addWidget(self.imageDown_check)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.version_label = QtGui.QLabel(Dialog)
        self.version_label.setGeometry(QtCore.QRect(440, 390, 54, 12))
        self.version_label.setObjectName("version_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "场集工具", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "集", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "场", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "工程", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Nuke路径", None, QtGui.QApplication.UnicodeUTF8))
        self.nukeButton.setText(QtGui.QApplication.translate("Dialog", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "服务器路径", None, QtGui.QApplication.UnicodeUTF8))
        self.serverButton.setText(QtGui.QApplication.translate("Dialog", "浏览", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "生成色板", None, QtGui.QApplication.UnicodeUTF8))
        self.sheetButton.setText(QtGui.QApplication.translate("Dialog", "创建色板", None, QtGui.QApplication.UnicodeUTF8))
        self.csheetUp_check.setText(QtGui.QApplication.translate("Dialog", "创建后上传色板", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "上传下载视频/单帧", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadButton.setText(QtGui.QApplication.translate("Dialog", "同步", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "上传", None, QtGui.QApplication.UnicodeUTF8))
        self.videoUp_check.setText(QtGui.QApplication.translate("Dialog", "视频", None, QtGui.QApplication.UnicodeUTF8))
        self.imageUp_check.setText(QtGui.QApplication.translate("Dialog", "单帧", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "下载", None, QtGui.QApplication.UnicodeUTF8))
        self.videoDown_check.setText(QtGui.QApplication.translate("Dialog", "视频", None, QtGui.QApplication.UnicodeUTF8))
        self.imageDown_check.setText(QtGui.QApplication.translate("Dialog", "单帧", None, QtGui.QApplication.UnicodeUTF8))
        self.version_label.setText(QtGui.QApplication.translate("Dialog", "version", None, QtGui.QApplication.UnicodeUTF8))

